#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CHE9000WAP.Resource", IsApplication=true)]

namespace CHE9000WAP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int ClientQueryApply_BACK = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int ClientQueryApply_BOARDBYPHOTE = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int ClientQueryApply_BOARDBYPIC = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int ClientQueryApply_CARCLASS = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int ClientQueryApply_CARDBYPHONE = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ClientQueryApply_CARDBYPIC = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int ClientQueryApply_CARTYPE = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int ClientQueryApply_IMGBOARD = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int ClientQueryApply_IMGCARD = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int ClientQueryApply_QUERYPRICE = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ClientQueryApply_SUBMIT = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int ClientQueryConfrm_Back = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int ClientQueryConfrm_QUERYPRICE = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int ClientQueryConfrm_SUBMIT = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int ClientUserInfo_BANK = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int ClientUserInfo_EXIT = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int Flash_ImgEnter = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int LoginPass_BACK = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int LoginPass_GETTELMARK = 2131034139;
			
			// aapt resource value: 0x7f05001f
			public const int LoginPass_SUBMIT = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int LoginPass_USERPASSCONFRM = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int LoginPass_USERPASSWORD = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int LoginPass_USERTEL = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int LoginPass_USERTELMARK = 2131034140;
			
			// aapt resource value: 0x7f050029
			public const int LoginRegArea_Back = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int LoginRegArea_Next = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int LoginRegArea_TITLE = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int LoginRegArea_USERCHECK = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int LoginRegBank_BACK = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int LoginRegBank_BANKLIST = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int LoginRegBank_USERBANKNO = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int LoginRegBank_USERSKIP = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int LoginRegBank_USERSUBMIT = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int LoginRegCarType_Back = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int LoginRegCarType_Next = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int LoginRegCarType_TITLE = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int LoginRegCarType_USERCHECK = 2131034165;
			
			// aapt resource value: 0x7f050020
			public const int LoginReg_Back = 2131034144;
			
			// aapt resource value: 0x7f050024
			public const int LoginReg_GETTELMARK = 2131034148;
			
			// aapt resource value: 0x7f050021
			public const int LoginReg_REGTYPECLIENT = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int LoginReg_REGTYPESERVE = 2131034146;
			
			// aapt resource value: 0x7f050028
			public const int LoginReg_SUBMIT = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int LoginReg_USERPASSCONFRM = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int LoginReg_USERPASSWORD = 2131034150;
			
			// aapt resource value: 0x7f050023
			public const int LoginReg_USERTEL = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int LoginReg_USERTELMARK = 2131034149;
			
			// aapt resource value: 0x7f05000c
			public const int Login_EXIT = 2131034124;
			
			// aapt resource value: 0x7f050016
			public const int Login_GETPASS = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int Login_REGTYPECLIENT = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int Login_REGTYPESERVE = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int Login_REGUSER = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int Login_USERLOGIN = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int Login_USERNAME = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int Login_USERPASS = 2131034131;
			
			// aapt resource value: 0x7f050038
			public const int MainClient_CHANGEPASS = 2131034168;
			
			// aapt resource value: 0x7f05003c
			public const int MainClient_CHECK = 2131034172;
			
			// aapt resource value: 0x7f05003a
			public const int MainClient_EXIT = 2131034170;
			
			// aapt resource value: 0x7f050039
			public const int MainClient_EXITALL = 2131034169;
			
			// aapt resource value: 0x7f05003d
			public const int MainClient_ORDERLIST = 2131034173;
			
			// aapt resource value: 0x7f05003b
			public const int MainClient_QUERY = 2131034171;
			
			// aapt resource value: 0x7f050036
			public const int MainClient_USERINFO = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int MainClient_USERMONEY = 2131034167;
			
			// aapt resource value: 0x7f050040
			public const int MainServe_CHANGEPASS = 2131034176;
			
			// aapt resource value: 0x7f050045
			public const int MainServe_CHECK = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int MainServe_CHECKLIST = 2131034182;
			
			// aapt resource value: 0x7f050042
			public const int MainServe_EXIT = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int MainServe_EXITALL = 2131034177;
			
			// aapt resource value: 0x7f050043
			public const int MainServe_QUERY = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int MainServe_QUERYLIST = 2131034180;
			
			// aapt resource value: 0x7f05003e
			public const int MainServe_USERINFO = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int MainServe_USERMONEY = 2131034175;
			
			// aapt resource value: 0x7f050048
			public const int ServeUserInfo_AREA = 2131034184;
			
			// aapt resource value: 0x7f05004a
			public const int ServeUserInfo_BANK = 2131034186;
			
			// aapt resource value: 0x7f050049
			public const int ServeUserInfo_CARTYPE = 2131034185;
			
			// aapt resource value: 0x7f050047
			public const int ServeUserInfo_EXIT = 2131034183;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClientCheckApply = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ClientCheckConfrm = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClientCheckList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ClientMoneyBack = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ClientMoneyList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ClientQueryApply = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ClientQueryConfrm = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ClientQueryList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ClientQueryPay = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ClientQueryPayConfrm = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ClientQueryPayPass = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ClientUserInfo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Flash = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Login = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int LoginPass = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int LoginReg = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LoginRegArea = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int LoginRegBank = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int LoginRegCarType = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int MainClient = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int MainServe = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ServeCheckGrab = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ServeCheckList = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ServeMoneyList = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int ServeMoneyMain = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int ServeMoneyOne = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int ServeQueryGrab = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int ServeQueryList = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ServeUserInfo = 2130903068;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
