#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CHE9000WAP.Resource", IsApplication=true)]

namespace CHE9000WAP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040012
			public const int bbutton_danger = 2130968594;
			
			// aapt resource value: 0x7f040016
			public const int bbutton_danger_disabled = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int bbutton_danger_disabled_edge = 2130968599;
			
			// aapt resource value: 0x7f040013
			public const int bbutton_danger_edge = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int bbutton_danger_pressed = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int bbutton_danger_pressed_edge = 2130968597;
			
			// aapt resource value: 0x7f04002a
			public const int bbutton_default = 2130968618;
			
			// aapt resource value: 0x7f04002e
			public const int bbutton_default_disabled = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int bbutton_default_disabled_edge = 2130968623;
			
			// aapt resource value: 0x7f04002b
			public const int bbutton_default_edge = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int bbutton_default_pressed = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int bbutton_default_pressed_edge = 2130968621;
			
			// aapt resource value: 0x7f04000a
			public const int bbutton_edittext_border = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int bbutton_edittext_disabled = 2130968587;
			
			// aapt resource value: 0x7f040024
			public const int bbutton_info = 2130968612;
			
			// aapt resource value: 0x7f040028
			public const int bbutton_info_disabled = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int bbutton_info_disabled_edge = 2130968617;
			
			// aapt resource value: 0x7f040025
			public const int bbutton_info_edge = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int bbutton_info_pressed = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int bbutton_info_pressed_edge = 2130968615;
			
			// aapt resource value: 0x7f040030
			public const int bbutton_inverse = 2130968624;
			
			// aapt resource value: 0x7f040034
			public const int bbutton_inverse_disabled = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int bbutton_inverse_disabled_edge = 2130968629;
			
			// aapt resource value: 0x7f040031
			public const int bbutton_inverse_edge = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int bbutton_inverse_pressed = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int bbutton_inverse_pressed_edge = 2130968627;
			
			// aapt resource value: 0x7f04000c
			public const int bbutton_primary = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int bbutton_primary_disabled = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int bbutton_primary_disabled_edge = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int bbutton_primary_edge = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int bbutton_primary_pressed = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int bbutton_primary_pressed_edge = 2130968591;
			
			// aapt resource value: 0x7f040018
			public const int bbutton_success = 2130968600;
			
			// aapt resource value: 0x7f04001c
			public const int bbutton_success_disabled = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int bbutton_success_disabled_edge = 2130968605;
			
			// aapt resource value: 0x7f040019
			public const int bbutton_success_edge = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int bbutton_success_pressed = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int bbutton_success_pressed_edge = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int bbutton_warning = 2130968606;
			
			// aapt resource value: 0x7f040022
			public const int bbutton_warning_disabled = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int bbutton_warning_disabled_edge = 2130968611;
			
			// aapt resource value: 0x7f04001f
			public const int bbutton_warning_edge = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int bbutton_warning_pressed = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int bbutton_warning_pressed_edge = 2130968609;
			
			// aapt resource value: 0x7f040006
			public const int bggray = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int blue = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int bluetgray = 2130968581;
			
			// aapt resource value: 0x7f040036
			public const int bthumbnail_background = 2130968630;
			
			// aapt resource value: 0x7f040038
			public const int bthumbnail_border = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int bthumbnail_font = 2130968633;
			
			// aapt resource value: 0x7f040037
			public const int bthumbnail_placeholder = 2130968631;
			
			// aapt resource value: 0x7f040000
			public const int darkgray = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int deeporange = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int lightgray = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int lightred = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int orange = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int white = 2130968585;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_edittext = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_edittext_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_edittext_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_menu = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_menu_act = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_search = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_search_act = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_setting = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_setting_act = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_share = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_share_act = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_user = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_user_act = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int shape_black = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int shape_bottom_corner_no_top_line = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int shape_button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int shape_no_corner_without_bottom = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int shape_top_corner_no_bottom_line = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int ClientQueryApply_BACK = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int ClientQueryApply_BOARDBYPHOTE = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int ClientQueryApply_BOARDBYPIC = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int ClientQueryApply_CARCLASS = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int ClientQueryApply_CARDBYPHONE = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int ClientQueryApply_CARDBYPIC = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int ClientQueryApply_CARTYPE = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int ClientQueryApply_IMGBOARD = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int ClientQueryApply_IMGCARD = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int ClientQueryApply_QUERYPRICE = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int ClientQueryApply_SUBMIT = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int ClientQueryConfrm_Back = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int ClientQueryConfrm_QUERYPRICE = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int ClientQueryConfrm_SUBMIT = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int ClientUserInfo_BANK = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int ClientUserInfo_EXIT = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int Flash_ImgEnter = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int LoginPass_BACK = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int LoginPass_GETTELMARK = 2131099678;
			
			// aapt resource value: 0x7f060022
			public const int LoginPass_SUBMIT = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int LoginPass_USERPASSCONFRM = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int LoginPass_USERPASSWORD = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int LoginPass_USERTEL = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int LoginPass_USERTELMARK = 2131099679;
			
			// aapt resource value: 0x7f06002d
			public const int LoginRegArea_Back = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int LoginRegArea_Next = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int LoginRegArea_TITLE = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int LoginRegArea_USERCHECK = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int LoginRegBank_BACK = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int LoginRegBank_BANKLIST = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int LoginRegBank_USERBANKNO = 2131099699;
			
			// aapt resource value: 0x7f060035
			public const int LoginRegBank_USERSKIP = 2131099701;
			
			// aapt resource value: 0x7f060034
			public const int LoginRegBank_USERSUBMIT = 2131099700;
			
			// aapt resource value: 0x7f060036
			public const int LoginRegCarType_Back = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int LoginRegCarType_Next = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int LoginRegCarType_TITLE = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int LoginRegCarType_USERCHECK = 2131099705;
			
			// aapt resource value: 0x7f060023
			public const int LoginReg_Back = 2131099683;
			
			// aapt resource value: 0x7f060027
			public const int LoginReg_GETTELMARK = 2131099687;
			
			// aapt resource value: 0x7f060024
			public const int LoginReg_REGTYPECLIENT = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int LoginReg_REGTYPESERVE = 2131099685;
			
			// aapt resource value: 0x7f06002b
			public const int LoginReg_SUBMIT = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int LoginReg_USERPASSCONFRM = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int LoginReg_USERPASSWORD = 2131099689;
			
			// aapt resource value: 0x7f060026
			public const int LoginReg_USERTEL = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int LoginReg_USERTELMARK = 2131099688;
			
			// aapt resource value: 0x7f06000c
			public const int Login_EXIT = 2131099660;
			
			// aapt resource value: 0x7f060018
			public const int Login_GETPASS = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int Login_REGTYPECLIENT = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int Login_REGTYPESERVE = 2131099675;
			
			// aapt resource value: 0x7f060017
			public const int Login_REGUSER = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int Login_RadioGroup = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int Login_USERLOGIN = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int Login_USERNAME = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int Login_USERPASS = 2131099669;
			
			// aapt resource value: 0x7f06003a
			public const int MainClient_Back = 2131099706;
			
			// aapt resource value: 0x7f060041
			public const int MainClient_CHANGEPASS = 2131099713;
			
			// aapt resource value: 0x7f06003d
			public const int MainClient_CHECK = 2131099709;
			
			// aapt resource value: 0x7f060043
			public const int MainClient_EXIT = 2131099715;
			
			// aapt resource value: 0x7f060042
			public const int MainClient_EXITALL = 2131099714;
			
			// aapt resource value: 0x7f06003e
			public const int MainClient_ORDERLIST = 2131099710;
			
			// aapt resource value: 0x7f06003c
			public const int MainClient_QUERY = 2131099708;
			
			// aapt resource value: 0x7f06003f
			public const int MainClient_USERINFO = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int MainClient_USERMONEY = 2131099712;
			
			// aapt resource value: 0x7f06003b
			public const int MainClient_user = 2131099707;
			
			// aapt resource value: 0x7f06004c
			public const int MainServe_CHANGEPASS = 2131099724;
			
			// aapt resource value: 0x7f060048
			public const int MainServe_CHECK = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int MainServe_CHECKLIST = 2131099721;
			
			// aapt resource value: 0x7f06004e
			public const int MainServe_EXIT = 2131099726;
			
			// aapt resource value: 0x7f06004d
			public const int MainServe_EXITALL = 2131099725;
			
			// aapt resource value: 0x7f060046
			public const int MainServe_QUERY = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int MainServe_QUERYLIST = 2131099719;
			
			// aapt resource value: 0x7f06004a
			public const int MainServe_USERINFO = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int MainServe_USERMONEY = 2131099723;
			
			// aapt resource value: 0x7f060044
			public const int MainServer_Back = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int MainServer_user = 2131099717;
			
			// aapt resource value: 0x7f060050
			public const int ServeUserInfo_AREA = 2131099728;
			
			// aapt resource value: 0x7f060052
			public const int ServeUserInfo_BANK = 2131099730;
			
			// aapt resource value: 0x7f060051
			public const int ServeUserInfo_CARTYPE = 2131099729;
			
			// aapt resource value: 0x7f06004f
			public const int ServeUserInfo_EXIT = 2131099727;
			
			// aapt resource value: 0x7f060012
			public const int textView1 = 2131099666;
			
			// aapt resource value: 0x7f06002c
			public const int top_bar = 2131099692;
			
			// aapt resource value: 0x7f060013
			public const int top_text = 2131099667;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClientCheckApply = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ClientCheckConfrm = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClientCheckList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ClientMoneyBack = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ClientMoneyList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ClientQueryApply = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ClientQueryConfrm = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ClientQueryList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ClientQueryPay = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ClientQueryPayConfrm = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ClientQueryPayPass = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ClientUserInfo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Flash = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Login = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int LoginPass = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int LoginReg = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LoginRegArea = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int LoginRegBank = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int LoginRegCarType = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int MainClient = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int MainServe = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ServeCheckGrab = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ServeCheckList = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ServeMoneyList = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int ServeMoneyMain = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int ServeMoneyOne = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int ServeQueryGrab = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int ServeQueryList = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ServeUserInfo = 2130903068;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int getpasstitle = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int regtitle = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
